# Generated by Django 3.1.3 on 2020-11-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201114_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default='location', on_delete=django.db.models.deletion.CASCADE, to='gallery.location'),
        ),
    ]
